name: Manual workflow
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  test:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Print Event Details
      run:  |
          echo "Event name: ${{ github.event_name }}"
          echo "Event ID: ${{ github.event.id }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Repository Owner: ${{ github.repository_owner }}"
          echo "Repository Name: ${{ github.repository }}"
    - name: getting
      run: |
        curl -D- -u truthsoftripura@gmail.com:Challenge@1 -X GET -H "Content-Type: application/json" http://truthsoftripura.atlassian.net/rest/api/3/issue/createmeta
        #curl --request GET --url "https://freelancertest.atlassian.net/rest/api/3/issue/FREEL-1" --user "chiranjib.nita@gmail.com:ATATT3xFfGF0-U1OLsYeWWshD7YBJW8lIS01VjDWjYLCDstuXXB3UGgp4Jnyu-hd8ae-L5Fn8PwcICyk4dZ3tRqkKbp3FXt6OWb9D6RWJYzGjUlZ6BUP2_hrZD4Gnp70mhoxsAK_8G1aFqUulpDX31y5LoDzBBf1FKlRKYwXj9-_XxwxGwXBxKE=0B970373" --header 'Accept: application/json' --header 'Content-Type: application/json'
