name: Manual workflow
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      key:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'JIRA ID'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  test:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: getting
      run: "curl --request GET --url "https://freelancertest.atlassian.net/rest/api/3/issue/FREEL-1" --user "chiranjib.nita@gmail.com:ATATT3xFfGF0-U1OLsYeWWshD7YBJW8lIS01VjDWjYLCDstuXXB3UGgp4Jnyu-hd8ae-L5Fn8PwcICyk4dZ3tRqkKbp3FXt6OWb9D6RWJYzGjUlZ6BUP2_hrZD4Gnp70mhoxsAK_8G1aFqUulpDX31y5LoDzBBf1FKlRKYwXj9-_XxwxGwXBxKE=0B970373" --header 'Accept: application/json' --header 'Content-Type: application/json'"
      
